"""Download CC-licensed images for individual brainrot characters.

Companion to scripts/download-category-images.py — same MediaWiki Commons
flow, but searches the character name directly. Many characters have no
Commons entries (their imagery is AI-generated by anonymous TikTok creators
with unclear ownership), so this script is deliberately tolerant of misses:
it reports what it found, what it skipped due to license, and what wasn't
indexed at all.

Output:
  assets/characters/<slug>.jpg     — image (or .png) when downloadable
  data/character-images-credits.json — full attribution + license per slug

DESIGN_NOTES.md hard rule: avoid copyright-risky territory. We only keep
results whose declared license is one of the safe set below.
"""
from __future__ import annotations

import json
import time
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "assets" / "characters"
CREDITS_PATH = ROOT / "data" / "character-images-credits.json"

USER_AGENT = (
    "DoYouEvenBrainrot/0.1 "
    "(https://github.com/leo020202-svg/do-you-even-brainrot; dev)"
)

# Licenses we'll keep. Anything else (e.g. "Fair use", "CC-BY-NC", "All rights
# reserved", or no license string at all) is skipped — we don't want to ship
# imagery we can't legally bundle.
SAFE_LICENSE_PREFIXES = (
    "cc-by",          # CC-BY, CC-BY-SA, CC-BY-X.Y, etc.
    "public domain",
    "pd-",
    "cc0",
)

# Search slug → list of query strings to try in priority order. First one that
# returns a hit + safe license wins. Order matters: most-specific name first,
# then a softer query if the specific one misses.
CHARACTERS: dict[str, list[str]] = {
    "tralalero-tralala": [
        "Tralalero Tralala",
        "Italian brainrot shark",
    ],
    "bombardiro-crocodilo": [
        "Bombardiro Crocodilo",
        "Italian brainrot crocodile bomber",
    ],
    "ballerina-cappuccina": [
        "Ballerina Cappuccina",
        "Italian brainrot ballerina",
    ],
    "tung-tung-tung-sahur": [
        "Tung Tung Tung Sahur",
        "Italian brainrot Sahur",
    ],
    "brr-brr-patapim": [
        "Brr Brr Patapim",
        "Italian brainrot Patapim",
    ],
    "lirili-larila": [
        "Lirili Larila",
        "Lirilì Larilà",
        "Italian brainrot elephant cactus",
    ],
    "bombombini-gusini": [
        "Bombombini Gusini",
        "Italian brainrot goose bomber",
    ],
    "cappuccino-assassino": [
        "Cappuccino Assassino",
        "Italian brainrot cappuccino",
    ],
    "frigo-camelo": [
        "Frigo Camelo",
        "Italian brainrot camel fridge",
    ],
    "trippi-troppi": [
        "Trippi Troppi",
        "Italian brainrot fish cat",
    ],
    "skibidi-toilet": [
        "Skibidi Toilet",
        "Skibidi character",
    ],
}


def is_safe_license(license_str: str | None) -> bool:
    if not license_str:
        return False
    lic = license_str.strip().lower()
    return any(lic.startswith(p) for p in SAFE_LICENSE_PREFIXES)


def commons_search_image(query: str, width: int = 640) -> dict | None:
    params = {
        "action": "query",
        "format": "json",
        "generator": "search",
        "gsrnamespace": "6",
        "gsrsearch": f"filetype:bitmap {query}",
        "gsrlimit": "3",
        "prop": "imageinfo",
        "iiprop": "url|user|extmetadata|mime",
        "iiurlwidth": str(width),
    }
    url = "https://commons.wikimedia.org/w/api.php?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = json.load(r)
    pages = data.get("query", {}).get("pages", {})
    if not pages:
        return None
    # Iterate pages by their search rank.
    sorted_pages = sorted(
        pages.values(),
        key=lambda p: p.get("index", 9999),
    )
    for page in sorted_pages:
        info_list = page.get("imageinfo") or []
        if not info_list:
            continue
        info = info_list[0]
        ext = info.get("extmetadata", {}) or {}
        lic = (ext.get("LicenseShortName") or {}).get("value")
        candidate = {
            "title": page.get("title", ""),
            "url": info.get("thumburl") or info.get("url"),
            "descurl": info.get("descriptionurl"),
            "user": info.get("user"),
            "license": lic,
            "credit": (ext.get("Credit") or {}).get("value"),
            "artist": (ext.get("Artist") or {}).get("value"),
            "mime": info.get("mime"),
            "_safe": is_safe_license(lic),
        }
        if candidate["_safe"]:
            return candidate
        # Hold onto an unsafe candidate to report — but keep scanning others.
        if "_first_unsafe" not in locals():
            _first_unsafe = candidate  # type: ignore[misc]
    return locals().get("_first_unsafe")  # may be None


def download(url: str, dest: Path) -> None:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=60) as r:
        data = r.read()
    dest.write_bytes(data)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    credits: dict[str, dict] = {}
    summary = {"downloaded": [], "skipped_license": [], "no_results": []}

    for slug, queries in CHARACTERS.items():
        hit: dict | None = None
        winning_query: str | None = None
        for q in queries:
            print(f"[{slug}] searching: {q!r}")
            try:
                candidate = commons_search_image(q)
            except Exception as e:  # noqa: BLE001
                print(f"  ERROR: {e}")
                continue
            if not candidate:
                continue
            if candidate.get("_safe"):
                hit = candidate
                winning_query = q
                break
            # Remember the unsafe one in case nothing else turns up.
            if hit is None:
                hit = candidate
                winning_query = q

        if not hit or not hit.get("url"):
            print(f"  no result for {slug}")
            summary["no_results"].append(slug)
            continue

        if not hit.get("_safe"):
            print(f"  skipping {slug}: license {hit.get('license')!r} not in safe set")
            summary["skipped_license"].append(
                {"slug": slug, "license": hit.get("license"), "title": hit["title"]}
            )
            continue

        ext = ".png" if "png" in (hit.get("mime") or "") else ".jpg"
        dest = OUT_DIR / f"{slug}{ext}"
        print(f"  downloading {hit['url']}")
        try:
            download(hit["url"], dest)
        except Exception as e:  # noqa: BLE001
            print(f"  ERROR downloading: {e}")
            continue
        credits[slug] = {
            "title": hit["title"],
            "descurl": hit["descurl"],
            "user": hit.get("user"),
            "license": hit.get("license"),
            "credit_html": hit.get("credit"),
            "artist_html": hit.get("artist"),
            "source": "Wikimedia Commons",
            "matched_query": winning_query,
        }
        print(f"  saved {dest.relative_to(ROOT)} ({dest.stat().st_size} bytes)")
        summary["downloaded"].append(slug)
        time.sleep(0.5)  # rate-limit politely

    CREDITS_PATH.parent.mkdir(parents=True, exist_ok=True)
    CREDITS_PATH.write_text(json.dumps(credits, indent=2), encoding="utf-8")

    print("\n=== summary ===")
    print(f"downloaded:       {summary['downloaded']}")
    print(f"skipped_license:  {[s['slug'] for s in summary['skipped_license']]}")
    print(f"no_results:       {summary['no_results']}")
    print(f"\nwrote credits to {CREDITS_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
